SayLove/config/routes.rb
SayLove::Application.routes.draw do

  get '/login' => 'accounts#login'
  get '/faq' => 'accounts#faq'
  get '/settings' => 'accounts#settings'
  post '/settings' => 'accounts#settings_update'

  get "/mobile" => 'mobile#index'

  get '/search/:type/:name' => 'accounts#search'

  get '/notifications' => 'profiles#notifications'

  get '/logout' => 'sessions#destroy'

  match "/auth/:provider/callback" => "sessions#oauth_success"
  match "/auth/failure" => "sessions#oauth_failure"

  resources :letters do
    member do
      get :flower
      get :favorite
    end

    resources :comments, :only => [:create]
  end

  get '/echobox' => 'letters#echobox'
  get '/sentbox' => 'letters#sentbox'
  get '/favorites' => 'letters#favorites'
  get '/write' => 'letters#new'
  get '/recent' => 'letters#index'
  get '/hot' => 'letters#hot'

  root :to => 'welcome#index', :constraints => lambda {|r| r.session[:user_id].nil? }
  root :to => 'letters#index'

end

SayLove/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @page_id = 'welcome'

    render 'index', :layout => false
  end
end

SayLove/app/helpers/welcome_helper.rb
module WelcomeHelper
end

SayLove/app/views/welcome/index.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "zh"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title Say Love - Where True Hearts Meet
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag "bootstrap.min", "welcome", :media => "all"
    = javascript_include_tag "modernizr-2.5.3.min"
    = csrf_meta_tags
  %body
    = render "shared/global_header"
    #wrapper.container.intro
      = image_tag "home.png", :class => 'girl'
      .rules
        %p 没有勇气表白？
        %p 在这里你可以给 Ta 写信，
        %p 如果 Ta 也写信给你，
        %p 那么双方就能收到彼此的信。
        %p 否则，Ta 永远都不会知道你写过信。
        %p
          = link_to "写信给 Ta >", write_path, {:id => 'write_btn'}
      .meta
        = link_to "登录", login_path
        \|
        = link_to "随便看看", recent_path
    = render "shared/global_footer"