SayLove/config/routes.rb
SayLove::Application.routes.draw do

  get '/login' => 'accounts#login'
  get '/faq' => 'accounts#faq'
  get '/settings' => 'accounts#settings'
  post '/settings' => 'accounts#settings_update'

  get "/mobile" => 'mobile#index'

  get '/search/:type/:name' => 'accounts#search'

  get '/notifications' => 'profiles#notifications'

  get '/logout' => 'sessions#destroy'

  match "/auth/:provider/callback" => "sessions#oauth_success"
  match "/auth/failure" => "sessions#oauth_failure"

  resources :letters do
    member do
      get :flower
      get :favorite
    end

    resources :comments, :only => [:create]
  end

  get '/echobox' => 'letters#echobox'
  get '/sentbox' => 'letters#sentbox'
  get '/favorites' => 'letters#favorites'
  get '/write' => 'letters#new'
  get '/recent' => 'letters#index'
  get '/hot' => 'letters#hot'

  root :to => 'welcome#index', :constraints => lambda {|r| r.session[:user_id].nil? }
  root :to => 'letters#index'

end

SayLove/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  require 'open-uri'

  before_filter :require_login, :only => [:search]

  def login
    @page_id = 'login'
    
    session[:return_to] = params[:url] if params[:url].present?
  end

  def faq
    @page_id = 'faq'

    render 'faq', :layout => 'profiles'
  end

  def settings
    @page_id = 'settings'

    @user = User.find(session[:user_id])

    render 'settings', :layout => 'profiles'
  end

  def settings_update
    @page_id = 'settings'

    email = params[:email]
    option_echo = params[:echo]
    option_flower = params[:flower]
    option_comment = params[:comment]

    @user = User.find(session[:user_id])

    if email.present?
      @user.email = email if @user.email != email
    elsif @user.email.blank?
      @user.email = 'can not be blank'
    end

    if option_echo.present?
      @user.email_option.echo = option_echo
    elsif @user.email_option.echo == true
      @user.email_option.echo = false
    end

    if option_flower.present?
      @user.email_option.flower = option_flower
    elsif @user.email_option.flower == true
      @user.email_option.flower = false
    end

    if option_comment.present?
      @user.email_option.comment = option_comment
    elsif @user.email_option.comment == true
      @user.email_option.comment = false
    end

    respond_to do |format|
      if @user.save && @user.email_option.save
        format.html { redirect_to settings_path, :notice => (t :save_success)}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'settings', :layout => 'profiles' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def search
    # test if the user input is a valid sns user
    
    @user = User.find(session[:user_id])
    
    contact_type = params[:type]
    contact_name = params[:name]

    result = 'ok'
    user_id = ''

    if contact_type.present? && contact_name.present?
      case contact_type
      when 'douban'
        begin
          stream = open('http://api.douban.com/v2/user/' + contact_name +'?apikey=0e5122e5aaf4e3ec2af368b100deabc4')
          if (stream.status.first == '200')
            info = JSON.parse(stream.read)

            if info['id'].present?
              user_id = info['id']
            else
              result = 'not_exist'
            end
          else
            result = 'error'
          end
        rescue => e
          result = 'not_exist'
        end

      when 'weibo'
        begin
          stream = open('https://api.weibo.com/2/users/show.json?screen_name=' + URI.encode(contact_name) +'&source=911483792')

          if (stream.status.first == '200')
            info = JSON.parse(stream.read)

            if info['idstr'].present?
              user_id = info['idstr']
            else
              result = 'not_exist'
            end
          else
            result = 'error'
          end
        rescue => e
          result = 'not_exist'
        end

      end
    else
      result = 'error'
    end

    respond_to do |format|
      if 'ok' == result
        format.json { render json: {:status => 0, :id => user_id}, status: :ok}
      elsif 'not_exist' == result
        format.json { render json: {:status => -1} }
      elsif 'error' == result
        format.json { render json: {:status => -2} }
      end
    end

  end
end

SayLove/app/helpers/accounts_helper.rb
module AccountsHelper
end

SayLove/app/views/accounts/faq.html.haml
.faq
  %h2 常见问题
  .section
    %h3 Say Love 是什么？
    %p 通俗一点来说，Say Love 是一个「情书支付宝」。如果你喜欢一个人又不敢向 Ta 表白，可以在这里给 Ta 写信，然后把 Say Love 推荐给 Ta 。如果 Ta 也写信给你，那么你们就会收到彼此的信，否则 Ta 永远都不会知道你曾经写过信。
    %p 技术只能帮助你降低一些风险，比如说，你可能不想失去一个好朋友，但是它无法完全替代一些东西。在偷偷写信和当面表白之间，如果你足够喜欢一个人的话，相信你有勇气做出正确的选择。
  .section
    %h3 我有微博账号，也有豆瓣账号，那么这两个账号算是同一个人吗？
    %p
      不算。每个不同社交网络账号都会被认为是不同的用户，以后可能会允许用户把自己的身份连通起来，但目前还不可以。所以如果你用豆瓣账号给 Ta 写信，而 Ta 给你的微博账号回信，那么你们肯定
      %strong 不会
      收到对方的信，切记切记。
  .section#why_email
    %h3 为什么回音不能以豆邮或私信的方式在豆瓣/微博通知我？
    %p 现在豆瓣和微博的 API 都采用了 OAuth2.0 协议，所以用户授权会有过期时间，也就是说如果你写信之后一个月没有登录，授权可能就会过期。这个时候如果对方回信给你，系统就没办法再通过你的授权给你发消息了。
    %p
      由于上面提到的无法克服的技术因素。如果你想要收到回信提醒，建议在
      = link_to '这里', settings_path
      设置一下自己的邮箱，Say Love 绝对不会未经允许向你发送邮件。
  .section
    %h3 你会在后台偷偷看我们的信吗？
    %p 当然不会啦！
  .section
    %h3 如何表达对这个应用的喜爱？
    %p
      如果你喜欢 Logo, 首页或者 favicon, 请到
      = link_to '设计师的豆瓣', 'http://www.douban.com/people/desolatelin/', :target => '_blank'
      感谢她。
    %p
      如果你喜欢网站的其它的部分，请到
      = link_to '微博', 'http://weibo.com/zhuoqun', :target => '_blank'
      或
      = link_to '豆瓣', 'http://www.douban.com/people/DreamerWang/', :target => '_blank'
      夸我两句就行了，文体不限。
  .section
    %h3 如何提交意见或反馈？
    %p
      你可以
      = link_to '发邮件', 'mailto:zhuoqunwang@gmail.com'
      给我，或者在
      = link_to '微博', 'http://weibo.com/zhuoqun', :target => '_blank'
      或
      = link_to '豆瓣', 'http://www.douban.com/people/DreamerWang/', :target => '_blank'
      给我留言。先行谢过。

SayLove/app/views/accounts/login.html.haml
.row.login
  .span12
    %h2 请登录后继续访问
    %ul.social.clearfix
      %li
        = link_to (image_tag "douban_login.png", {:alt => "使用豆瓣账号登录"}), "/auth/douban"
      %li
        = link_to (image_tag "weibo_login.png", {:alt => "使用微博账号登录"}), "/auth/weibo"
      %li.last
        = link_to (image_tag "mobile_login.png", {:alt => "使用手机账号登录"}), mobile_path

SayLove/app/views/accounts/settings.html.haml
.settings
  = form_tag settings_path, :class => 'form-horizontal' do
    %legend 设置
    - if flash[:notice].present?
      .alert.alert-success
        = flash[:notice]
    - if @user.email.present? && @user.errors.blank?
      .control-group.my-email
        = label_tag :email, '邮箱：', :class => 'control-label'
        .controls.js-display
          %span#email
            = @user.email
          %span.help-inline
            = link_to '修改', '#', :class => 'js-edit'
        .controls.js-edit.hide
          = text_field_tag :email, @user.email
    - else
      - error = @user.errors.blank? ? '' : 'error'
      - message = @user.errors.messages[:email].blank? ? '' : @user.errors.messages[:email].first
      .control-group{:class => error}
        = label_tag :email, '邮箱：', :class => 'control-label'
        .controls
          = text_field_tag :email, params[:email]
          %span.help-inline
            = message
    .control-group
      = label_tag :email_options, '接收邮件设置：', :class => 'control-label'
      .controls
        %label.checkbox{:for => "echo"}
          = check_box_tag :echo, 1, @user.email_option.echo
          我的信有了回音
        %label.checkbox{:for => "flower"}
          = check_box_tag :flower, 1, @user.email_option.flower
          有人送祝福给我
        %label.checkbox{:for => "comment"}
          = check_box_tag :comment, 1, @user.email_option.comment
          有人评论了我的信
    .control-group.why-not-sns
      .controls
        = link_to '为什么不使用豆瓣/微博的站内通知？', faq_path + '#why_email', :target => '_blank'
    .form-actions
      = submit_tag '保存设置', {:class => 'btn btn-primary'}