SayLove/config/routes.rb
SayLove::Application.routes.draw do

  get '/login' => 'accounts#login'
  get '/faq' => 'accounts#faq'
  get '/settings' => 'accounts#settings'
  post '/settings' => 'accounts#settings_update'

  get "/mobile" => 'mobile#index'

  get '/search/:type/:name' => 'accounts#search'

  get '/notifications' => 'profiles#notifications'

  get '/logout' => 'sessions#destroy'

  match "/auth/:provider/callback" => "sessions#oauth_success"
  match "/auth/failure" => "sessions#oauth_failure"

  resources :letters do
    member do
      get :flower
      get :favorite
    end

    resources :comments, :only => [:create]
  end

  get '/echobox' => 'letters#echobox'
  get '/sentbox' => 'letters#sentbox'
  get '/favorites' => 'letters#favorites'
  get '/write' => 'letters#new'
  get '/recent' => 'letters#index'
  get '/hot' => 'letters#hot'

  root :to => 'welcome#index', :constraints => lambda {|r| r.session[:user_id].nil? }
  root :to => 'letters#index'

end

SayLove/app/views/shared/_global_footer.html.haml
%footer.container
  .row
    .span8
      %p
        %span © 2012 SAY LO♥E
        %span.siteinfo
          = link_to '常见问题', faq_path
          •
          = link_to '联系我们', 'mailto:zhuoqunwang@gmail.com'
        %span
          Handmade by
          = link_to 'zhuoqun', 'http://www.zhuoqun.net', :target => '_blank'
          &
          = link_to 'Lin', 'http://www.douban.com/people/desolatelin/', :target => '_blank'
    .span4.principle
      %p We want to touch your heart and make you smile.
%script
  :plain
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36090848-1']);
    _gaq.push(['_setDomainName', 'isaylove.com']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

SayLove/app/views/shared/_global_header.html.haml
%header.container.title
  .row
    .span6
      %h1
        = link_to "Say Love", root_path, :id => 'logo'
        %span Where True Hearts Meet
    .span6
      - if @page_id != 'welcome'
        %ul.menu
          - if session[:user_id].nil?
            - nav_items = global_nav_items_unlog_in
          - else
            - nav_items = global_nav_items_logged_in
          - nav_items.each do |nav|
            - active = @page_id == nav[:id] ? 'active' : ''
            - unread_count = nav[:unread_count].blank? ? '' : "(#{nav[:unread_count]})"
            %li
              %a{:href => nav[:url], :class => active}
                = t("page_#{nav[:id]}".to_sym) + unread_count

SayLove/app/views/shared/_letter_meta.html.haml
.meta.clearfix
  .left
    - if has_sent_flower?(letter.id)
      %a.js-flower.active{:href => "#"}
        %i.icon-gift
        %span 已祝福 #{letter.flowers_cnt}
    - else
      %a.js-flower{:href => "#"}
        %i.icon-gift
        %span 祝福 #{letter.flowers_cnt}
    - if has_favorited?(letter.id)
      %a.js-favorite.favorited{:href => "#"}
        %i.icon-heart
        %span 已收藏
    - else
      %a.js-favorite{:href => "#"}
        %i.icon-heart
        %span 收藏
    %a.view{:href => "#{letter_path(letter.id)}", :style => "display:none"}
      %i.icon-eye-open
      %span 查看此信
  .right
    - if letter.comments_on
      %a{:href => "#{letter_path(letter.id)}#comments"}
        %i.icon-comment
        %span 评论 #{letter.comments.count}
    - else
      %span.off 评论已关闭
    %a.share{:href => "#"}
      %i.icon-share-alt
      %span 分享
    .sharebox
      #bdshare.bdshare_t.bds_tools.get-codes-bdshare{:data => "{'url':'#{letter_url(letter)}', 'text':'转自@SayLove应用 ：#{truncate_letter_content(letter.content)}'}"}
        %a.bds_douban
        %a.bds_tsina
        %a.bds_renren
        %a.bds_tqq
        %a.bds_ff
        %a.bds_qzone
        %a.bds_tieba
        %a.bds_t163
        %a.bds_diandian
        %a.bds_kaixin001
      .arrow