SayLove/config/routes.rb
SayLove::Application.routes.draw do

  get '/login' => 'accounts#login'
  get '/faq' => 'accounts#faq'
  get '/settings' => 'accounts#settings'
  post '/settings' => 'accounts#settings_update'

  get "/mobile" => 'mobile#index'

  get '/search/:type/:name' => 'accounts#search'

  get '/notifications' => 'profiles#notifications'

  get '/logout' => 'sessions#destroy'

  match "/auth/:provider/callback" => "sessions#oauth_success"
  match "/auth/failure" => "sessions#oauth_failure"

  resources :letters do
    member do
      get :flower
      get :favorite
    end

    resources :comments, :only => [:create]
  end

  get '/echobox' => 'letters#echobox'
  get '/sentbox' => 'letters#sentbox'
  get '/favorites' => 'letters#favorites'
  get '/write' => 'letters#new'
  get '/recent' => 'letters#index'
  get '/hot' => 'letters#hot'

  root :to => 'welcome#index', :constraints => lambda {|r| r.session[:user_id].nil? }
  root :to => 'letters#index'

end

SayLove/app/models/letter.rb
class Letter < ActiveRecord::Base
  attr_accessible :comments_on, :contact_id, :contact_type, :content, :disable, :is_draft, :is_public, :is_viewed, :notified, :user_id, :has_echo, :flowers_cnt

  before_save :check_echos

  validates :user_id, :contact_id, :contact_type, :content, :presence => true

  default_scope where('letters.disable = ?', false)
  scope :recent_letters, where('is_public = ?', true).order('created_at DESC')
  scope :hot_letters, where('is_public = ?', true).order('flowers_cnt DESC, created_at DESC')

  belongs_to :user
  has_many :comments
  has_many :flowers
  has_many :favorites

  def self.favorited_by_user_id(user_id)
    joins(:favorites).where('favorites.user_id' => user_id).order('favorites.created_at DESC')
  end

  def self.echo_letters_by_user(user)
    where('contact_type' => user.provider.provider, 'contact_id' => user.provider.uid, 'has_echo' => true).order('created_at DESC')
  end

  def self.unread_echo_letters_by_user(user)
    where('contact_type' => user.provider.provider, 'contact_id' => user.provider.uid, 'has_echo' => true, 'is_viewed' => false).count
  end

  def check_echos
    current_user = User.find(user_id)
    echo_user = User.joins(:provider).where('providers.uid' => contact_id, 'providers.provider' => contact_type)
    if echo_user.present?
      echo_letters = echo_user.first.letters.where('contact_id' => current_user.provider.uid, 'contact_type' => current_user.provider.provider)
      if echo_letters.present?
        self.has_echo = true

        echo_letters.update_all(:has_echo => true)
      end
    end
  end
end

SayLove/app/controllers/letters_controller.rb
class LettersController < ApplicationController

  before_filter :require_login
  skip_before_filter :require_login, :only => [:index, :hot, :show]

  def index
    if session[:user_id].nil?
      @page_id = 'random'
    else
      @page_id = 'index'
    end

    @submenu = 'recent'

    @letters = Letter.recent_letters.paginate(:page => params[:page])
  end

  def hot
    if session[:user_id].nil?
      @page_id = 'random'
    else
      @page_id = 'index'
    end

    @submenu = 'hot'

    @letters = Letter.hot_letters.paginate(:page => params[:page])

    render 'index'
  end

  def echobox
    @page_id = 'echobox'

    current_user = User.find(session[:user_id])

    if current_user.from_provider
      @letters = Letter.echo_letters_by_user(current_user).paginate(:page => params[:page])

      # mark all as read
      Letter.echo_letters_by_user(current_user).update_all(:is_viewed => true)
    end
  end

  def sentbox
    @page_id = 'sentbox'

    current_user = User.find(session[:user_id])

    @letters = current_user.letters.order('created_at DESC').paginate(:page => params[:page])
  end

  def favorites
    @page_id = 'favorites'

    @letters = Letter.favorited_by_user_id(session[:user_id]).paginate(:page => params[:page])
  end

  def show
    @letter = Letter.find(params[:id])

    if session[:user_id].blank?
      if !(@letter.is_public)
        redirect_to root_path
      end
    else
      current_user = User.find(session[:user_id])
      if !(@letter.is_public || @letter.user_id.to_i == current_user.id ||
        (@letter.has_echo && @letter.contact_type == current_user.provider.provider && @letter.contact_id == current_user.provider.uid))

        redirect_to root_path
      end
    end

    @comments = @letter.comments.paginate(:page => params[:page])
  end

  def new

    @quote = Quote.offset(rand(Quote.count)).first

    @draft = cookies[session[:user_id]].blank? ? '' : cookies[session[:user_id]]

    render "new", :layout => false
  end

  def create
    @letter = Letter.new
    @letter.user_id = session[:user_id]
    @letter.contact_id = params[:userid]
    @letter.contact_type = params[:account_type]
    @letter.content = params[:content]

    @letter.content = '<p>' + @letter.content + '</p>'
    @letter.content = @letter.content.gsub(/\r\n/, '</p><p>')

    if (params[:public].present? && params[:public] == '1')
      @letter.is_public = true
    end

    if (params[:commentson].present? && params[:commentson] == '1')
      @letter.comments_on = true
    end

    respond_to do |format|
      if @letter.save
        format.html { render "create", :layout => "accounts" }
        format.json { render json: @letter, status: :created, location: @letter }
      else
        @letter.content = @letter.content.gsub(/<\/p><p>/, "\r\n")
        @letter.content = @letter.content.gsub(/<\/p>/, '')
        @letter.content = @letter.content.gsub(/<p>/, '')

        format.html { render action: "new" }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end

  end

  def favorite
    # add or delete favorite
    letter_id = params[:id]

    existed = Favorite.find_by_user_id_and_letter_id(session[:user_id], letter_id)
    action = ''

    if existed.present?
      # cancel favorite
      action = 'cancel'

      existed.destroy
    else
      # add favorite
      action = 'add'

      favorite = Favorite.new
      favorite.user_id = session[:user_id]
      favorite.letter_id = letter_id
      favorite.save
    end

    respond_to do |format|
      if 'cancel' == action
        format.json { render json: {:status => 0}, status: :ok}
      elsif 'add' == action
        format.json { render json: {:status => 0}, status: :created}
      end
    end

  end

  def flower
    # send flower
    letter_id = params[:id]

    existed = Flower.find_by_user_id_and_letter_id(session[:user_id], letter_id)
    action = ''

    if existed.present?
      # no change
      action = 'nochange'
    else
      # add favorite
      action = 'add'

      flower = Flower.new
      flower.user_id = session[:user_id]
      flower.letter_id = letter_id

      if flower.save
        add_notification(Letter.find(letter_id).user.id, letter_id, 'flower')
      end
    end

    respond_to do |format|
      if 'nochange' == action
        format.json { render json: {:status => -1}, status: :not_acceptable}
      elsif 'add' == action
        format.json { render json: {:status => 0, :count => Letter.find(letter_id).flowers.count}, status: :created}
      end
    end

  end

end

SayLove/app/helpers/letters_helper.rb
module LettersHelper
end

SayLove/app/views/letters/create.html.haml
.row.login
  .span12
    %h2 发送成功！你可以到发件箱中查看发出的信。
    - if current_user.email.blank?
      = link_to '设置邮箱，获取回音通知', settings_path

SayLove/app/views/letters/echobox.html.haml
- if @letters.blank?
  .letter
    .content
      %p 你暂时还没有收到回信。
- @letters.each do |letter|
  .letter{"data-letter-id" => letter.id}
    .content
      = sanitize letter.content
    .author
      Ta 的 #{t(letter.user.provider.provider.to_sym)}：
      = link_to letter.user.provider.url, letter.user.provider.url, {:target => '_blank'}
    - if letter.is_public
      = render :partial => 'shared/letter_meta', :locals => { :letter => letter }
    - else
      .meta.clearfix
        .left
          %span.off 此信没有公开
          %a.view{:href => "#{letter_path(letter.id)}", :style => "display:none"} 查看此信
= will_paginate @letters, :class => "pagination pagination-centered"

SayLove/app/views/letters/favorites.html.haml
- if @letters.blank?
  .letter
    .content
      %p 你还没有收藏过任何信。
- @letters.each do |letter|
  .letter{"data-letter-id" => letter.id}
    .content
      = sanitize letter.content
    = render :partial => 'shared/letter_meta', :locals => { :letter => letter }
= will_paginate @letters, :class => "pagination pagination-centered"

SayLove/app/views/letters/index.html.haml
.submenu
  查看：
  - if @submenu == 'recent'
    %span 最近
    \/
    = link_to "热门", hot_path
  - elsif @submenu == 'hot'
    = link_to "最近", recent_path
    \/
    %span 热门
- @letters.each do |letter|
  .letter{"data-letter-id" => letter.id}
    .content
      = sanitize letter.content
    = render :partial => 'shared/letter_meta', :locals => { :letter => letter }
= will_paginate @letters, :class => "pagination pagination-centered"

SayLove/app/views/letters/new.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "zh"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title 写信 | Say Love - Where True Hearts Meet
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag "bootstrap.min", "letters", :media => "all"
    = javascript_include_tag "modernizr-2.5.3.min"
    = csrf_meta_tags
  %body
    = render "shared/global_header"
    / Help Modal
    #helpModal.modal.hide{"aria-hidden" => "true", "aria-labelledby" => "helpModalLabel", :role => "dialog"}
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h3#helpModalLabel 如何找到对方的用户名或 ID ？
      .modal-body
        %ul#helpTab.nav.nav-tabs
          %li.active
            %a.help-weibo{:href => "#help_weibo"} 新浪微博
          %li
            %a.help-douban{:href => "#help_douban"} 豆瓣网
        .tab-content
          #help_weibo.tab-pane.active
            %p 可以用 @ 提到的即是 Ta 的新浪微博用户名，如图：
            = image_tag "uid_weibo.png"
          #help_douban.tab-pane
            %p 点击到 Ta 的豆瓣主页，网址中的最后那个部分即是 Ta 的豆瓣 ID，如图:
            = image_tag "uid_douban.png"
    .container
      .wrapper
        .row
          .span12
            .write
              = form_tag letters_path, :class => 'form-horizontal' do
                %legend 写信
                .control-group.my-account
                  = label_tag :my_account, '我的账号', :class => 'control-label'
                  .controls
                    %span#my_account #{get_provider_display_name}: #{current_user.user_name}
                    = hidden_field_tag :my_uid, current_user.id
                .control-group
                  = label_tag :account_type, 'Ta 的帐号类型', :class => 'control-label'
                  .controls
                    = select_tag :account_type, options_for_select([['新浪微博', 'weibo'], ['豆瓣网', 'douban']])
                .control-group.username
                  = label_tag :username, 'Ta 的新浪微博账号', :class => 'control-label'
                  .controls
                    = text_field_tag :username
                    = hidden_field_tag :userid
                    %span.help-inline.js-help
                      = link_to '如何找到对方的新浪微博账号？', '#helpModal', {'data-toggle' => 'modal'}
                    %span.help-inline.js-search.hide
                      = image_tag 'loading.gif', {:class => 'loading'}
                      = image_tag 'correct.png', {:class => 'correct'}
                      %span 正在验证用户是否存在...
                .control-group
                  = label_tag :content, '内容', :class => 'control-label'
                  .controls
                    = text_area_tag :content, @draft
                    %span.help-block.quote
                      = @quote.content
                .control-group
                  %label.control-label 设置
                  .controls
                    %label.checkbox{:for => "public"}
                      = check_box_tag :public
                      公开到首页 (不会显示你的名字)
                .control-group.comments-setting.hide
                  .controls
                    %label.checkbox.inline{:for => "commentson"}
                      = check_box_tag :commentson, 1
                      允许评论
                .form-actions
                  = submit_tag '送出', {:class => 'btn btn-primary publish', :disabled => true}
                  %button.btn{:type => "button"} 取消
                  - if current_user.email.blank?
                    = link_to '设置邮箱，获取回音通知', settings_path, :target => '_blank', :class => 'set-email'
    = render "shared/global_footer"
    = javascript_include_tag "write"

SayLove/app/views/letters/sentbox.html.haml
- if @letters.blank?
  .letter
    .content
      %p 你还没有写过信。
- @letters.each do |letter|
  .letter{"data-letter-id" => letter.id}
    .content
      = sanitize letter.content
    - if letter.is_public
      = render :partial => 'shared/letter_meta', :locals => { :letter => letter }
    - else
      .meta.clearfix
        .left
          %span.off 此信没有公开
          %a.view{:href => "#{letter_path(letter.id)}", :style => "display:none"} 查看此信
= will_paginate @letters, :class => "pagination pagination-centered"

SayLove/app/views/letters/show.html.haml
.letter{"data-letter-id" => @letter.id}
  .content
    = sanitize @letter.content
  - if @letter.is_public
    = hidden_field_tag :single, 1
    = render :partial => 'shared/letter_meta', :locals => { :letter => @letter }
  - else
    .meta.clearfix
      .left
        %span.off 此信没有公开

- if @letter.is_public
  .comments-area
    .arrow
    - active = @letter.comments_on ? '' : 'active'
    %ul#commentsTab.nav.nav-tabs
      %li{:class => active}
        %a{:href => "#flowers"} 祝福 (#{@letter.flowers_cnt})
      - if @letter.comments_on
        %li.active
          %a{:href => "#comments"} 评论 (#{@comments.count})
    .tab-content
      #flowers.tab-pane{:class => active}
        - if @letter.flowers.count <= 0
          %p 暂时还没有人祝福。
        - else
          %p
            来自：
            - @letter.flowers.each_with_index do |flower, index|
              = link_to flower.user.user_name, flower.user.provider.url, {:target => '_blank'}
              - if index + 1 < @letter.flowers_cnt
                ，
      - if @letter.comments_on
        #comments.tab-pane.active
          - if @comments.count <= 0
            %p 暂时还没有人评论。
          - else
            %ul.list
              - @comments.each do |comment|
                %li.clearfix
                  %a.avatar{:href => "#{comment.user.provider.url}"}
                    %img{:height => "20px", :src => "#{comment.user.avatar}", :width => "20px"}/
                  .comment-body
                    = link_to comment.user.user_name, comment.user.provider.url
                    \:
                    = sanitize comment.content
            = will_paginate @comments, :class => "pagination pagination-centered"
  - if @letter.comments_on
    - if current_user
      #comment_input.comment-input.clearfix
        %h3 添加评论
        %a.avatar{:href => "#{current_user.provider.url}"}
          %img{:height => "30px", :src => "#{current_user.avatar}", :width => "30px"}/
        .body
          = form_tag letter_comments_path(@letter.id), :class => 'form-horizontal' do
            %textarea{:name => 'content'}
            .ctrl.clearfix
              = submit_tag '发布', {:class => 'btn publish', :disabled => true}
    - else
      #comment_input.comment-input.clearfix
        %h3
          请
          = link_to '登录', login_path + '?url=' + letter_path(@letter)
          后评论